require "faraday"
require "hashie"
require "nokogiri"
require "active_support/core_ext/string"
require "searchbing"

require "whos_dated_who/version"
require "whos_dated_who/biography"
require "whos_dated_who/parser"
require "whos_dated_who/bing_client"
require "whos_dated_who/client"
